CREATE DATABASE simplepp;
USE DATABASE simplepp;
CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at VARCHAR(255) NOT NULL,
    document VARCHAR(255) NOT NULL UNIQUE,
    document_type VARCHAR(50) NOT NULL
);